### ISSUE TITLE
publishing configuration file fails

### ISSUE THREAD

**Issue by torniker** [andersao/laravel-repository#3]
In laravel 5 php artisan config:publish is not valid command, you have in your readme that it is possible to publish configuration using that command, but it fails.

I also tried to use 
- php artisan vendor:publish --provider="prettus/laravel-repository"
- php artisan vendor:publish --provider="prettus/laravel-repository" --tag="config"
- php artisan vendor:publish --provider="Prettus\Repository\RepositoryServiceProvider"
  but could not publish your configuration file.

Update:
Solved problem needed to remove quotes :)
the following command worked:
php artisan vendor:publish --provider=Prettus\Repository\RepositoryServiceProvider

**Comment by andersao** [comment]
Hello Torniker , for Laravel 5 I created a new project with some other improvements. See on https://github.com/andersao/l5-repository

**Comment by andersao** [comment]
torniker , I will fix it ;)
